# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-26 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogspost',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
